#!/bin/bash

set -e

export iOSOpenDevPath="/opt/iOSOpenDev"

[[ -d "$iOSOpenDevPath/bin" ]] || \
	mkdir -p "$iOSOpenDevPath/bin"

scriptPath="$iOSOpenDevPath/bin/iod-setup"

curl -L https://github.com/profiles/iOSOpenDev-Installer/raw/master/scripts/iod-setup -o "$scriptPath"
chmod +x "$scriptPath"

if [[ -f "$scriptPath" ]]; then
	echo "Running $scriptPath..."
	"$scriptPath" base
	"$scriptPath" sdk -sdk iphoneos
	"$scriptPath" sdk -sdk iphonesimulator

	exit 0
else
	echo "$scriptPath not found!"

	rm -rf "$sourceDir"
	exit 1
fi
